# 1.4.5 Morphological Transformations

## 1. Erosion

In [9]:
import cv2
import numpy as np

In [10]:
def showImage(img):
    cv2.imshow('image',img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [11]:
img = cv2.imread('./img/Char/image01.jpg',0)
img = 255-img;

In [12]:
kernel = np.ones((3,3),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)

In [37]:
showImage(erosion)

## 2. Dilation

In [38]:
kernel = np.ones((3,3),np.uint8)
dilation = cv2.dilate(img,kernel,iterations = 1)

In [39]:
showImage(dilation)

## 3. Opening

In [40]:
height, width = img.shape
m = 1
noise_img = img.copy()
for i in range(100):
    x = np.random.randint(width)
    y = np.random.randint(height)
    noise_img[y-m:y+m,x-m:x+m]=255

In [41]:
showImage(noise_img)

In [42]:
kernel = np.ones((3,3),np.uint8)
opening = cv2.morphologyEx(noise_img, cv2.MORPH_OPEN, kernel)

In [43]:
showImage(opening)

## 4. Closing

In [44]:
m = 1
noise_img = img.copy()
for i in range(1000):
    x = np.random.randint(width)
    y = np.random.randint(height)
    noise_img[y-m:y+m,x-m:x+m]=0

In [45]:
showImage(noise_img)

In [46]:
kernel = np.ones((3,3),np.uint8)
closing = cv2.morphologyEx(noise_img, cv2.MORPH_CLOSE, kernel)

In [47]:
showImage(closing)

## 5. Morphological Gradient

In [48]:
kernel = np.ones((3,3),np.uint8)
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

In [49]:
showImage(gradient)

## 6. Top Hat

In [13]:
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)

In [15]:
showImage(tophat)

## 7. Black Hat

In [9]:
import cv2
import numpy as np

In [10]:
img = cv2.imread('Handwriting.jpg',0)
kernel = np.ones((5,5),np.uint8)
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

In [14]:
cv2.imshow('img',img)
cv2.imshow('blackhat',blackhat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [12]:
cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [13]:
cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)